
CREATE VIEW VIEW_USER_INFORMATION AS
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH,
       U.DAY_OF_BIRTH, U.GENDER, C.CURRENT_CITY, C.CURRENT_STATE, C.CURRENT_COUNTRY,
       H.HOMETOWN_CITY, H.HOMETOWN_STATE, H.HOMETOWN_COUNTRY, P.INSTITUTION_NAME,
       P.PROGRAM_YEAR, P.PROGRAM_CONCENTRATION, P.PROGRAM_DEGREE
FROM USERS U
    LEFT JOIN ( -- left join?
        SELECT e.USER_ID, e.PROGRAM_YEAR, p.INSTITUTION AS "INSTITUTION_NAME",
               p.CONCENTRATION AS "PROGRAM_CONCENTRATION", p.DEGREE AS "PROGRAM_DEGREE"
        FROM EDUCATION e
        JOIN PROGRAMS p
            ON p.PROGRAM_ID=e.PROGRAM_ID) P
        ON P.USER_ID=U.USER_ID
    LEFT JOIN ( --left join?
        SELECT r.USER_ID, c.CITY_NAME AS "CURRENT_CITY", c.STATE_NAME AS "CURRENT_STATE",
               c.COUNTRY_NAME AS "CURRENT_COUNTRY"
        FROM CITIES c 
        JOIN USER_CURRENT_CITIES r
            ON r.CURRENT_CITY_ID=c.CITY_ID) C
        ON C.USER_ID=U.USER_ID
    LEFT JOIN ( --left join?
        SELECT h.USER_ID, t.CITY_NAME AS "HOMETOWN_CITY", t.STATE_NAME AS "HOMETOWN_STATE",
               t.COUNTRY_NAME AS "HOMETOWN_COUNTRY"
        FROM CITIES t
        JOIN USER_HOMETOWN_CITIES h
            ON h.HOMETOWN_CITY_ID=t.CITY_ID) H
        ON H.USER_ID=U.USER_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT USER1_ID, USER2_ID
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT A.ALBUM_ID, A.ALBUM_OWNER_ID AS "OWNER_ID", A.COVER_PHOTO_ID, A.ALBUM_NAME,
       A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY,
       P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A
    JOIN PHOTOS P ON P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION,
       E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME AS "EVENT_CITY",
       C.STATE_NAME AS "EVENT_STATE", C.COUNTRY_NAME AS "EVENT_COUNTRY",
       E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E
    JOIN CITIES C
         ON C.CITY_ID=E.EVENT_CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT TAG_PHOTO_ID AS "PHOTO_ID", TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X AS "TAG_X_COORDINATE",
       TAG_Y AS "TAG_Y_COORDINATE"
FROM TAGS;