DROP TRIGGER order_friends_pairs;
DROP TRIGGER TRIGGER_PROGRAM;
DROP SEQUENCE PROGRAM_ID_SEQUENCE;
DROP TRIGGER TRIGGER_CITY;
DROP SEQUENCE CITY_ID_SEQUENCE;

ALTER TABLE PHOTOS
DROP CONSTRAINT PHOTOS_FK;

ALTER TABLE ALBUMS
DROP CONSTRAINT ALBUMS_FK;

DROP TABLE TAGS;
DROP TABLE ALBUMS;
DROP TABLE PHOTOS;
DROP TABLE PARTICIPANTS;
DROP TABLE EDUCATION;
DROP TABLE USER_EVENTS;
DROP TABLE MESSAGES;
DROP TABLE PROGRAMS;
DROP TABLE USER_HOMETOWN_CITIES;
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE CITIES;
DROP TABLE FRIENDS;
DROP TABLE USERS;